"""Description of changes

Revision ID: c35e6b9de06b
Revises: 
Create Date: 2024-11-27 02:18:47.463174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35e6b9de06b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'password',
               existing_type=sa.VARCHAR(length=72),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=72),
               existing_nullable=False)
    # ### end Alembic commands ###
